In [1]:
import numpy

In [6]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [3]:
pwd

'/net/il-galaxy.sanbi.ac.za/data/home/pvh'

In [5]:
cd

/net/il-galaxy.sanbi.ac.za/data/home/pvh


In [7]:
'.mBc18GrC.wV'

'.mBc18GrC.wV'

In [8]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [10]:
print('hello', 'everyone', sep='^^^^')

hello^^^^everyone


In [11]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [12]:
loadtxt(fname='data/inflammation-01.csv', delimiter=',')

NameError: name 'loadtxt' is not defined

In [13]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [14]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [15]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [16]:
print(type(data))

<class 'numpy.ndarray'>


In [17]:
weight_kg = 60
print(type(weight_kg))

<class 'int'>


In [19]:
weight_kg = 60.0
print(type(weight_kg))

<class 'float'>


In [20]:
weight_kg_txt = 'weight in kg:'
print(type(weight_kg_txt))

<class 'str'>


In [21]:
1 + 2.0

3.0

In [22]:
1 + 'hello'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [23]:
'hello' + 'everyone'

'helloeveryone'

In [26]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [24]:
print(data.dtype)

float64


In [25]:
print(data.shape)

(60, 40)


### Indices

In [27]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [30]:
print('first value in data:', data[0, 0])

first value in data: 0.0


In [29]:
print('middle value in data:', data[30, 20])

middle value in data: 13.0


In [34]:
print('row 2, column 1:', data[1, 0])

row 2, column 1: 0.0


In [35]:
print('row 5, column 10:', data[4, 9])

row 5, column 10: 4.0


### Slices

In [36]:
print(data[0:5, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]
 [0. 1. 1. 3. 3. 1. 3. 5. 2. 4.]]


In [37]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [38]:
print(data[:5, :10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]
 [0. 1. 1. 3. 3. 1. 3. 5. 2. 4.]]


In [39]:
print(data[30:, 36:])

[[2. 3. 2. 1.]
 [2. 3. 0. 0.]
 [2. 0. 2. 1.]
 [1. 2. 1. 1.]
 [2. 1. 1. 1.]
 [4. 2. 2. 0.]
 [4. 3. 2. 1.]
 [1. 0. 1. 0.]
 [1. 3. 0. 1.]
 [4. 3. 2. 1.]
 [3. 0. 0. 1.]
 [2. 2. 0. 0.]
 [2. 1. 2. 0.]
 [2. 1. 0. 1.]
 [4. 3. 1. 1.]
 [4. 1. 1. 0.]
 [1. 0. 0. 0.]
 [2. 1. 2. 1.]
 [4. 3. 0. 0.]
 [2. 2. 2. 1.]
 [4. 1. 2. 0.]
 [1. 3. 1. 0.]
 [4. 1. 2. 1.]
 [2. 2. 2. 1.]
 [1. 0. 0. 1.]
 [3. 3. 0. 1.]
 [2. 2. 1. 1.]
 [2. 1. 1. 1.]
 [2. 0. 2. 0.]
 [3. 1. 1. 0.]]


In [40]:
print(data[:3, 36:])

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [42]:
print(data[0, :70])

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


### Maths with numpy arrays

In [43]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [44]:
doubledata = data * 2.0

In [45]:
print(data)
print(doubledata)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
[[0. 0. 2. ... 6. 0. 0.]
 [0. 2. 4. ... 2. 0. 2.]
 [0. 2. 2. ... 4. 2. 2.]
 ...
 [0. 2. 2. ... 2. 2. 2.]
 [0. 0. 0. ... 0. 4. 0.]
 [0. 0. 2. ... 2. 2. 0.]]


In [46]:
tripledata = doubledata + data

In [47]:
print(tripledata)

[[0. 0. 3. ... 9. 0. 0.]
 [0. 3. 6. ... 3. 0. 3.]
 [0. 3. 3. ... 6. 3. 3.]
 ...
 [0. 3. 3. ... 3. 3. 3.]
 [0. 0. 0. ... 0. 6. 0.]
 [0. 0. 3. ... 3. 3. 0.]]


In [48]:
print(numpy.mean(data))

6.14875


In [51]:
print(numpy.mean(data[:1, :])) # the first row, all the columns

5.45


In [59]:
print(numpy.mean(data[:1]))  # leaving off the 2nd coordinate is equivalent to the cell above

5.45


In [56]:
print(numpy.std(data[:1, :])) # standard deviation

3.898397106504159


In [57]:
print(numpy.max(data[:1, :]))

18.0


In [58]:
print(numpy.min(data[:1, :]))

0.0
