In [1]:
weight_kg = 43
weight_lb = weight_kg * 2.2

In [2]:
def fahr_to_celsius(temp):
    return ((temp - 32) * (5/9))

In [3]:
print

<function print>

In [4]:
print()

In [5]:
fahr_temp = 100
celsius_temp = fahr_to_celsius(fahr_temp)
print(celsius_temp, "C is", fahr_temp, "F")

37.77777777777778 C is 100 F


In [6]:
def celsius_to_kelvin(temp_c):
    return temp_c + 273.15

In [7]:
fahr_temp = 32
kelvin_temp = celsius_to_kelvin(fahr_to_celsius(fahr_temp))
print(fahr_temp,"F is",kelvin_temp,"K")

32 F is 273.15 K


In [8]:
def fahr_to_celsius(temp):
    print((temp - 32) * (5/9))

In [9]:
fahr_temp = 100
celsius_temp = fahr_to_celsius(fahr_temp)
print(celsius_temp, "C is", fahr_temp, "F")

37.77777777777778
None C is 100 F


In [10]:
def word_type(word):
    if word == 'apple' or word == 'pear':
        return 'fruit'
    elif word == 'cucumber' or word == 'tomato':
        return 'vegetable'
    else:
        return 'unknown'
    print('done')


In [11]:
word = 'apple'
print(word, "is a", word_type(word))
word = 'tomato'
print(word, "is a", word_type(word))

apple is a fruit
tomato is a vegetable


In [12]:
import numpy
import glob

def detect_problems(filename):
    data = numpy.loadtxt(fname=filename, delimiter=',')
    
    if numpy.max(data, axis=0)[0] == 0 and numpy.max(data, axis=0)[20] == 20:
        print('Suspicious looking maxima!')
        return True
    else:
        print('Seems OK!')
        return False


In [13]:
detect_problems('data/inflammation-01.csv')

Suspicious looking maxima!


True

In [14]:
filenames = glob.glob('data/inflammation*.csv')
for filename in filenames:
    if not detect_problems(filename):
        print('Analyse this:', filename)

Suspicious looking maxima!
Seems OK!
Analyse this: data/inflammation-08.csv
Seems OK!
Analyse this: data/inflammation-03.csv
Suspicious looking maxima!
Suspicious looking maxima!
Suspicious looking maxima!
Seems OK!
Analyse this: data/inflammation-11.csv
Suspicious looking maxima!
Suspicious looking maxima!
Suspicious looking maxima!
Suspicious looking maxima!
Suspicious looking maxima!


### Testing and Documenting

In [15]:
def offset_mean(data, target_mean_value):
    return (data - numpy.mean(data)) + target_mean_value

In [16]:
zero = numpy.zeros((2))
print(zero)

[0. 0.]


In [17]:
print(offset_mean(zero, 5))

[5. 5.]


In [18]:
normal = numpy.random.normal(loc=0.0, scale=1.0, size=10)
print(normal)

[ 1.16014861  0.55592012 -1.16390572  0.54890835 -0.76079024  0.46945872
  2.69572665 -1.94224528  0.30743367 -0.09399161]


In [19]:
old_mean = normal.mean()
print(old_mean)

0.17766632775442234


In [20]:
adjusted_normal = offset_mean(normal, -old_mean)
print(adjusted_normal)

[ 0.80481596  0.20058747 -1.51923837  0.19357569 -1.1161229   0.11412606
  2.340394   -2.29757793 -0.04789898 -0.44932427]


In [21]:
print(adjusted_normal.mean())

-0.1776663277544223


In [22]:
def offset_mean(data, target_mean_value):
    """Adjust the mean of a numpy array so that the new mean is
       target_mean_value
       
       Parameters:
         data - numpy array
         target_mean_value - int or float: the new mean"""
    return (data - numpy.mean(data)) + target_mean_value

In [23]:
"hello"

'hello'

In [24]:
"hello
world"

SyntaxError: EOL while scanning string literal (<ipython-input-24-14238644de1f>, line 1)

In [ ]:
'''hello
world
'''

In [ ]:
help(offset_mean)

In [29]:
zero.mean(0)

0.0

In [30]:
adjusted = offset_mean(zero, 5)
print(adjusted.mean())

5.0


In [31]:
def test_offset_mean():
    zero = numpy.zeros(2)
    adjusted = offset_mean(zero, 5)
    assert adjusted.mean() == 5

In [32]:
test_offset_mean()

In [35]:
def offset_mean(data, target_mean_value):
    """Adjust the mean of a numpy array so that the new mean is
       target_mean_value
       
       Parameters:
         data - numpy array
         target_mean_value - int or float: the new mean"""
    return (data - numpy.mean(data)) + target_mean_value*2

In [36]:
adjusted = offset_mean(zero, 5)
print(adjusted.mean())

10.0


In [37]:
test_offset_mean()

AssertionError: 

In [38]:
def test_offset_mean():
    zero = numpy.zeros(2)
    adjusted = offset_mean(zero, 5)
    new_mean = adjusted.mean()
    assert new_mean == 5, "Got " + str(new_mean) + " expected 5"

In [39]:
test_offset_mean()

AssertionError: Got 10.0 expected 5

In [40]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [42]:
help(numpy.loadtxt)

Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
       

In [43]:
numpy.loadtxt('data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [44]:
numpy.loadtxt('data/inflammation-01.csv', ',')

SyntaxError: unexpected EOF while parsing (<string>, line 1)

In [50]:
def offset_mean(data, target_mean_value=0.0):
    """Adjust the mean of a numpy array so that the new mean is
       target_mean_value
       
       Parameters:
         data - numpy array
         target_mean_value - int or float: the new mean"""
    return (data - numpy.mean(data)) + target_mean_value

In [51]:
help(offset_mean)

Help on function offset_mean in module __main__:

offset_mean(data, target_mean_value=0.0)
    Adjust the mean of a numpy array so that the new mean is
    target_mean_value
    
    Parameters:
      data - numpy array
      target_mean_value - int or float: the new mean



In [52]:
offset_mean(zero, 5)

array([5., 5.])

In [49]:
offset_mean(zero, target_mean_value=5)

array([10., 10.])

In [53]:
offset_mean(zero)

array([0., 0.])

#### Exercises

1. Define a function `fence(word, char)` that returns the word surrounded by the character char. E.g. `fence('apple', '*')` returns `*apple*`

2. Define a function `outer(word)` that returns the outer characters of the word (remember `[0]` and `[-1]` indices). So `outer('helium')` would return `hm`

3. Define a function `rescale(array, min, max)` that takes a numpy array and returns the array rescaled so that all values lie between `min` and `max` (inclusive). (Hint: If `L` and `H` are the lowest and highest values in the original array, then the replacement for a value `v` should be `(v-L) / (H-L)`.)

4. Provide default values (e.g. `0` and `1`) for the `min` and `max` parameters in `rescale` using keyword arguments.

5. Write documentation and a test function for `rescale`.


#### Solutions

In [55]:
# 1. fence
def fence(word, char):
    return char + word + char

def test_fence():
    result = fence('star', '*')
    assert fence('star', '*') == '*star*', "expected *star* got " + result
    
test_fence()

In [57]:
# 2. outer
def outer(word):
    if len(word) < 2:
        return ''
    else:
        return word[0] + word[-1]

def test_outer():
    expected = 'hm'
    result = outer('helium')
    assert result == expected, "expected " + expected + " got " + result
    expected = ''
    result = outer('a')
    assert result == expected, "expected " + expected + " got " + result

test_outer()

In [68]:
# 3. rescale
import numpy

def rescale(array, min, max):
    orig_max = numpy.max(array)
    orig_min = numpy.min(array)
    new_range = max - min
    new_array = (array - orig_min) / (orig_max - orig_min) * new_range + min
    return new_array

def test_rescale():
    data = numpy.array([4.0, 5.0, 6.0])
    expected = numpy.array([1.0, 2.0, 3.0])
    result = rescale(data, 1, 3)
    assert result[0] == expected[0] and result[1] == expected[1] and result[2] == expected[2], "expected " + str(expected) + " got " + str(result)

test_rescale()

In [69]:
# 4. rescale
import numpy

def rescale(array, min=0, max=1):
    orig_max = numpy.max(array)
    orig_min = numpy.min(array)
    new_range = max - min
    new_array = (array - orig_min) / (orig_max - orig_min) * new_range + min
    return new_array

def test_rescale():
    data = numpy.array([4.0, 5.0, 6.0])
    expected = numpy.array([1.0, 2.0, 3.0])
    result = rescale(data, 1, 3)
    assert result[0] == expected[0] and result[1] == expected[1] and result[2] == expected[2], "expected " + str(expected) + " got " + str(result)

test_rescale()

#### Exercises discussion

In [70]:
word = 'apple'
char = '*'
expected = '*apple*'
result = char + word + char
print(expected, result)

*apple* *apple*
